/**
 * ----------------------------------------------------------------------------------
 * flo_coin.tsx
 * ----------------------------------------------------------------------------------
 *
 * @author shuangshuang 2024/4/11
 */

import * as styles from '@/module/home/flo_coin/flo_coin.css';

import { Box, Container, Grid, Icon, Typography } from '@mui/material';

import Icon1 from '@/assets/img//home/flo_coin/icon_1.svg';
import Icon2 from '@/assets/img//home/flo_coin/icon_2.svg';
import Icon3 from '@/assets/img//home/flo_coin/icon_3.svg';
import Icon4 from '@/assets/img//home/flo_coin/icon_4.svg';
import Icon5 from '@/assets/img//home/flo_coin/icon_5.svg';
import Icon6 from '@/assets/img//home/flo_coin/icon_6.svg';

// ----------------------------------------------------------------------------------
const dataList = [
  {
    icon: <Icon1 />,
    title: 'Event Ecosystem Currency',
    text: 'Purchase tickets, exclusive merchandise, and access unique events on the eventflo platform using FloCoin.',
  },
  {
    icon: <Icon2 />,
    title: 'Rewards & Incentives',
    text: 'Earn rewards through staking, referrals, and by actively participating in the eventflo community and events powered by eventflo.',
  },
  {
    icon: <Icon3 />,
    title: 'Enhanced Rewards',
    text: 'Holding FloCoin unlocks greater benefits, including better staking rewards and increased governance power.',
  },
  {
    icon: <Icon4 />,
    title: 'Governance',
    text: 'FloCoin holders have a say in platform development, ensuring its evolution aligns with the needs of both organizers and attendees.',
  },
  {
    icon: <Icon5 />,
    title: 'Strategic Buybacks',
    text: 'Revenue generated by the platform will be used to buy back FloCoin, supporting its long-term value.',
  },
  {
    icon: <Icon6 />,
    title: 'Commercial Activity',
    text: 'Businesses and creators needing to advertise or promote on the platform will drive consistent demand for FloCoin.',
  },
];
// ----------------------------------------------------------------------------------
export default function FloCoin() {
  // ----------------------------------------------------------------------------------
  return (
    <Box className={styles.bg}>
      <Container>
        <Typography className={styles.title}>FloCoin: The Future of Events</Typography>
        <Typography className={styles.subtitle}>Why FloCoin? Utility - Rewards - Growth Potential</Typography>
        <Typography className={styles.text}>
          FloCoin ignites a new era of event experience. Invest in FloCoin, and you're not only fueling innovation in
          event attendance & management, but also have the potential to directly benefit from its success.
        </Typography>
        <Grid container className={styles.list}>
          {dataList.map((data) => (
            <Grid key={data.text} flexGrow={1}>
              {data.icon}
              <Typography className={styles.itemTitle}>{data.title}</Typography>
              <Typography className={styles.itemText}>{data.text}</Typography>
            </Grid>
          ))}
        </Grid>
      </Container>
    </Box>
  );
}
